# Generated by Django 3.1.12 on 2022-10-25 02:58

import apiRest.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('idEdificio', models.SmallIntegerField(default=0, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('apodos', models.CharField(default='', max_length=100)),
                ('descripcion', models.CharField(default='', max_length=100)),
                ('pisos', djongo.models.fields.ArrayField(default='', model_container=apiRest.models.Piso)),
            ],
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('idNodo', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('edEntrada', models.SmallIntegerField()),
                ('cantidadPersonas', models.SmallIntegerField()),
                ('tipoEspacio', models.CharField(choices=[('grande', 'grande'), ('medio', 'mediano'), ('pequenio', 'pequeño')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('uId', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('nombre', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
