# Generated by Django 3.1.12 on 2022-11-07 02:05

import apiRest.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id_edificio', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('palabras_clave', models.CharField(max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.CharField(max_length=500, null=True)),
                ('aforoActual', models.IntegerField(default=0, null=True)),
                ('espacios', djongo.models.fields.ArrayField(model_container=apiRest.models.Espacio, null=True)),
                ('listaDeEntradas', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('idNodo', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('peso', models.IntegerField(default=0)),
                ('habilitado', models.BooleanField(default=False, null=True)),
                ('vecinos', models.CharField(max_length=500, null=True)),
                ('tipoEspacio', models.FloatField(default=1, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='edificio',
            index=models.Index(fields=['nombre'], name='apiRest_edi_nombre_a403b3_idx'),
        ),
        migrations.AddIndex(
            model_name='edificio',
            index=models.Index(fields=['palabras_clave'], name='apiRest_edi_palabra_f4fc14_idx'),
        ),
    ]
