# Generated by Django 4.1.1 on 2022-10-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SmallIntegerField(default=0)),
                ('nombre', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('imagen', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
